import = ["theme.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5}
opacity = 0.85

[scrolling]
history = 10000
multiplier = 5

[font]
# Font is setup in .config/fontconfig/fonts.conft
normal = { family = "terminal-font", style = "Regular" }
bold = { family = "terminal-font", style = "Bold" }
italic = { family = "terminal-font", style = "Italic" }
size = 9
offset = { x = 0, y = 0 }