#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
MAIN_MONITOR='eDP-1'

bspc monitor $MAIN_MONITOR -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

export WALLPAPER="$HOME/.config/bspwm/assets/wallpaper.png"

xsetroot -cursor_name left_ptr
bspc config focus_follows_pointer	true
bspc config automatic_scheme	spiral
bspc config pointer_modifier	mod1

bspc rule -a Chromium desktop='^2' follow=on


# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

feh --no-fehbg --bg-fill "$WALLPAPER" & # wallpaper
picom --config $HOME/.config/picom.conf & # compositor
dunst --config $HOME/.config/dunst/dunstrc & # notifications
bash $HOME/.config/polybar/launch.sh
# bash $HOME/.config/eww/bar/launch_bar
pulseaudio --start

## You can edit this.
BSPWM_BORDER='0'
BSPWM_GAP='10'

#function SetBspwmConf() {
#	bspc config border_width "$BSPWM_BORDER"
#	bspc config top_padding "$2"
#	bspc config bottom_padding "$3"
#	bspc config normal_border_color "$4" 
#	bspc config active_border_color "$5"
#	bspc config focused_border_color "$6"
#	bspc config presel_feedback_color "$7"
#	bspc config left_padding "$8"
#	bspc config right_padding "$9"
#	bspc config window_gap "$BSPWM_GAP"
#}



# SetBspwmConf "$BSPWM_BORDER" 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "$BSPWM_GAP"





# killeww


# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

# export WALLPAPER="$HOME/.config/bspwm/assets/wallpaper.png"
# export LOCKSCREEN_WALLPAPER="$HOME/.config/bspwm/assets/lockscreen.png"

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
# rule() { bspc rule -a "$@" & }
# config() { bspc config "$@" & }
# start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
# launch_eww() { $HOME/.local/bin/eww daemon & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Clear cache.
# rm $HOME/.cache/dunst.log
# rm $HOME/.cache/fake_battery_capacity
# rm $HOME/.cache/eww-calendar.lock
# rm $HOME/.cache/eww-escreen.lock
# rm $HOME/.cache/eww-control-center.lock
# rm -r $HOME/.cache/dunst/

# Fix cursor size.
# xsetroot -xcf /usr/share/icons/volantes-cursors/cursors/left_ptr 32

# Autostart applications.
# launch_eww && eww open bar
# pgrep -x sxhkd > /dev/null || sxhkd &
# dunst --config $HOME/.config/dunst/dunstrc &
# picom --config $HOME/.config/picom/picom.conf &

# Start polkit agent.
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# # Setup wallpaper.
# feh --no-fehbg --bg-fill "$WALLPAPER" &

# I hate mouse drift.
# xset m 0 0

# Fix for eww bar not hiding on a fullscreen window.
#pkill ewwFullscreenFix.sh; $HOME/.config/bspwm/scripts/ewwFullscreenFix.sh &
# Make Do Not Disturb and Night Light work after power on or reboot.
#pkill persistentQuickUtilities.sh; $HOME/.config/bspwm/scripts/persistentQuickUtilities.sh &

# Start MPD and mpDris2
# exec mpd &
# exec mpDris2 &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# bspc monitor -d 1 2 3 4 5

# rule firefoxdeveloperedition        desktop=1 follow=on
# rule Navigator                      desktop=1 follow=on

# rule discord                        desktop=2 follow=off
# rule Code                           desktop=3
# rule Steam                          desktop=4

# rule Viewnior                       state=floating
# rule mpv                            state=fullscreen follow=on

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

# config pointer_modifier             Mod4

# config window_gap                   16

# config top_padding                  0
# config left_padding                 0
# config right_padding                0
# config bottom_padding               48

# config split_ratio                  0.62
# config borderless_monocle           true
# config gapless_monocle              true

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

# start $HOME/.local/bin/brdr
# Fix windows being below bar
# xdo lower -N eww-bar
