[shell_alias]
cat    = 'bat'
vim    = 'nvim'
diff   = 'delta'
ls     = 'eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions'
la     = 'eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions -a'
python = 'python3'
ghx    = 'fnox exec -- gh'

[env]
XDG_DATA_HOME   = "{{env.HOME}}/.local/share"
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
XDG_STATE_HOME  = "{{env.HOME}}/.local/state"
# gcloud's bundled Python doesn't support macOS's system Python (3.9)
CLOUDSDK_PYTHON = "{{env.HOME}}/.local/share/mise/installs/python/latest/bin/python"
