[tools]
jq = "latest"
yq = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
zoxide = "latest"
ripgrep = "latest"
github-cli = "latest"
neovim = "latest"
lazygit = "latest"
starship = "latest"
usage = "latest"
fzf = "latest"
delta = "latest"
tealdeer = "latest"
glow = "latest"
atuin = "latest"
python = "latest"
uv = "latest"
fnox = "latest"
bitwarden = "latest"
age = "latest"
