default_provider = "age"
env = "exec"

[providers.bitwarden]
type = "bitwarden"

[providers.age]
type = "age"
recipients = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICP2g5weFd7pkYop0x7HKyVM/ribR8yeifcc6AM8FKnV fnox age"]
key_file = "~/.ssh/id_ed25519_age"

[secrets]
GH_TOKEN     = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtHUW5WQSBDM0NrSFdlWlZoNUY3cWpvVzN1Y2xxeFR4aFZnWXlTb3gwcTRya1QyZldnCmoyekNGR0dyZEdpcDZDck1JR0VYMGJYV1MvSE81Uy9yWFFzeUFLZzBFL2sKLT4gcUBTSEwtZ3JlYXNlIHggTThsRCByPGMxeEZoIGQxKF5hNQpJeUxmNkRpaUZXZUZoVG1GM1p1dDZxdzdqOUpDbG1Ja1dVWTdWUQotLS0gdWNkeXhLbGdUcXRrSlZOa1JycFo2ZTlLQWJTMnJPb25yOTQwK0x2amVxQQq5Qi+FOLRAu/J9GEE9jzKy2u0rtdWyo24M40HzjQeqY4vTeb52EYAAUmjIOD4t0UBi9Gfvuok33KWTF3TW9240hRJBvydHnUA=", env = true }
GITHUB_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtHUW5WQSBxTUJEeUUxNERScFpDK0ZYM2pJOTVKcURya1NmSlNEV3VXL1g0TlRkU3h3CmV6N0tiZ2dBL3dEVFduQXg1Sk5pUFdLWktBM2poSStLTkRRWWEvT21ObkEKLT4gTWwheFAtZ3JlYXNlCkhkRmFGcm5BbGRYdE1sc1lmd01jWGZESCtMMm0vdlJvV0xRc0xONzBrd21OZzdkS29sckpBVGhGR1N4ckVhMmUKSm9BdHVnS3IzeWRMRzQzVFdmNjFTSFUKLS0tIDlqZFRjTFdHMTFGM1h5T2xVdjdXaHNQVjgxakR5K2grSUpnNXE4ZllBeVkKewBBAywcX5fq5LUb73Zjt3qQ0ifktqj4l7CKiEpJV7N/+CC1rzPYPB09c6N/WRNbqLFRFqfOzVv/XXrI+LhZfmslIp1g6F9t", env = true }
AI_PROVIDER_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGtHUW5WQSBjaXk4MzJNV0FqV2hYYmgvUm9zUzZ3aDdHUFhhalJnMFZaa3JWcFdENm44CjZ1WmtZbWVzQkd6b1hvOGtyQVpJdk9Pc0ozSnFRYWtDVnNTUEZHTTZRTEUKLT4gUjNVYD9bSi1ncmVhc2UKRGlSR1pDdEpCSkFpVVE3YmZjOTBYTFg5bVFPeEVWWnFxMWdJcFRFNXh3RGZoYUptQUxIMFE4bGJ2UFVyV1BFawpNdDhxNEoxQ1VoOEdSblg0Y1VhdC9qU1FkQldCCi0tLSBJdmw0MUhpbmJuNE1hVDFsZnAvQ1oyMjdWcE15RlVHWURneXkyVGdpZ1BzCl3pThQyTOE4zIjhLyFV1QsUxCrOo9IdAaWZa9ar7vA19z/hA9zlCAH3G+3Rnmygw4aMTdj7UUEFVQ==" }
