default_provider = "bitwarden"

[providers.bitwarden]
type = "bitwarden"

[providers.age]
type = "age"
recipients = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICP2g5weFd7pkYop0x7HKyVM/ribR8yeifcc6AM8FKnV fnox age"]
key_file = "~/.ssh/id_ed25519_age"

[secrets]
GH_TOKEN     = { provider = "bitwarden", value = "GitHub CLI Token", env = "exec" }
GITHUB_TOKEN = { provider = "bitwarden", value = "GitHub CLI Token", env = "exec" }
