#!/bin/bash

STATUS=$(dunstctl is-paused)

toggle() {
    if [ $STATUS == "false" ]; then
        dunstctl set-paused toggle
    else
        dunstctl set-paused toggle
        dunstify --urgency=normal --appname=PeaceMode "Peace mode" "Notifications enabled"
    fi
}

icon() {
    if [ $STATUS == "false" ]; then
        echo "󰂜"
    else
        echo "󰪑"
    fi
}

status() {
    if [ $STATUS == "false" ]; then
        echo "Off"
    else
        echo "On"
    fi
}

class() {
    if [ $STATUS == "false" ]; then
        echo "off"
    else
        echo "on"
    fi
}


if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--class" ]]; then
    class
elif [[ $1 == "--status" ]]; then
    status
fi
