#!/sbin/zsh

is_active=$(pgrep gammastep)

toggle() {
    if [[ -n $is_active ]]; then
        pkill gammastep
    else
        gammastep &
    fi
}

icon() {
    if [[ -n $is_active ]]; then
        echo "󱩍"
    else
        echo "󰹐"
    fi
}

class() {
    if [[ -n $is_active ]]; then
        echo "on"
    else
        echo "off"
    fi 
}

status() {
    if [[ -n $is_active ]]; then
        echo "Turned on"
    else
        echo "Turned off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--class" ]]; then
    class
elif [[ $1 == "--status" ]]; then
    status
fi
